# Generated by Django 6.1 on 2026-08-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='preview_url',
        ),
        migrations.AddField(
            model_name='track',
            name='spotify_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
